# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d513920d9525e434c0d3f64c2b39cf7d84493019ec0fbfbdbac2373f2b08df7c079c82dd27dd029f2084d60f8b04c44f2812b87454167c4278e553a704985c9

test:
  secret_key_base: ad3c464b749c6c46f73d9ab35796d588dc47c02a89471c8a4ac0095fe33ba1a4e3f293311286705f3eeec23f653558bb2ddc232e9c04815926f5383e5db5bd17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
